site_name: pipelinedoc
theme:
  name: material
  palette:
    - scheme: default  # Tema claro padrão
      primary: black
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Mudar para modo escuro
    - scheme: slate  # Tema escuro
      primary: black
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Mudar para modo claro
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.expand  # Abre os menus automaticamente
    - toc.integrate  # Integra o sumário lateral na página
    - search.suggest
    - search.highlight
    - navigation.instant
    - toc.integrate
    - content.code.copy
repo_url: https://github.com/asn-vortx/pipelinedoc
nav:
  - Início: index.md
  - Biblioteca de Código:
      - Visão Geral: library/index.md
      - 1️⃣ Connection:
          - MongoDB: library/connection_mongodb.md
          - PostgreSQL: library/connection_postgres.md
          - SQL Server: library/connection_sqlserver.md
      - 2️⃣ Extract:
          - MongoDB: library/extract_from_mongo.md
          # - Athena: library/extract_from_athena.md (futuramente)
      - 3️⃣ Transform:
          - Transformações Gerais: library/transform.md
      - 4️⃣ Tests:
          - Testes e Validações: library/tests.md
      - 5️⃣ Load:
          - Carga de Dados: library/load.md
      - 6️⃣ IaC:
          - Terraform & Infraestrutura: library/iac.md
markdown_extensions:
  - pymdownx.highlight:
      linenums: true   # Exibe números nas linhas do código
      anchor_linenums: true  # Permite clicar nos números das linhas
      auto_title: true  # Adiciona título no código
      use_pygments: true  # Usa Pygments para coloração avançada
  - pymdownx.superfences